name: Build yuedu_source file
on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install python package
        run: |
          pip install --upgrade pip wheel
          pip install demjson
          pip install requests
          echo "::set-env name=RELEASE_NAME::Released on $(date +%Y%m%d%H%M)"
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: makefile
        run: |
          python makefile.py
          mkdir -p ./publish
          mv ./bing_wallpaper.crx ./publish/
          mv ./bing_wallpaper.json ./publish/

      - name : upload
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: bing
          path: ./publish/